---
title: "GreenDeck Ratings"
author: "Aaron Guerra"
date: "12/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(tidyverse)
library(lubridate)
library(data.table)
```

```{r}
gd <- read.csv("gd-evals-clean-2.csv")
gd$Timestamp = parse_date_time(gd$Timestamp, c("mdy HMS", "mdy"))
gd$Timestamp = as.POSIXct(gd$Timestamp) # convert timestamp
gd <- gd %>%  rename(variable=Rating.Category, value = Rating) #rename variables
gd <- gd %>% # resassign Bh to B and Ph to P'
  mutate(Species = case_when(
    Species == "B" ~ "Bg",
    Species == "P'" ~ "Ph",
    TRUE ~ Species))
unique(gd$Species)
```

```{r}
gd_means <- gd %>% group_by(Species, variable) %>% summarise(mean = mean(value,na.rm = TRUE))
gd_o_means <- gd_means %>% filter(variable == "Overall Appearance")
```

```{r}
start_dates <- c("4/1", "6/1", "6/1", "4/1", "2/1", "8/1", "2/1", "6/1", "3/1", "6/1", "5/1", "3/1")
start_dates21 <- as.POSIXct(strptime(paste0(start_dates, "/21"), "%m/%d/%y"))
start_dates22 <- as.POSIXct(strptime(paste0(start_dates, "/22"), "%m/%d/%y"))
start_dates23 <- as.POSIXct(strptime(paste0(start_dates, "/23"), "%m/%d/%y"))

end_dates <- c("8/31", "7/31", "7/31", "7/31", "9/30", "10/31", "4/30", "7/31", "8/31", "8/31", "7/31", "5/31")
end_dates21 <- as.POSIXct(strptime(paste0(end_dates, "/21"), "%m/%d/%y"))
end_dates22 <- as.POSIXct(strptime(paste0(end_dates, "/22"), "%m/%d/%y"))
end_dates23 <- as.POSIXct(strptime(paste0(end_dates, "/23"), "%m/%d/%y"))

plants <- c('Am', 'As', 'B', 'Cp', 'Eu', 'Ec', 'Fc', 'Fi', 'Mb', 'Mv', 'P', 'Sb') 

gd_p <- setNames(as.list(rep(NA, length(plants))), plants) #create empty df with keys = plant names

df_sd <- as.data.frame(cbind(start_dates21, start_dates22, start_dates23)) #start date
row.names(df_sd) <- plants

df_ed <- as.data.frame(cbind(end_dates21, end_dates22, end_dates23)) # end date
row.names(df_ed) <- plants

for (i in plants) {
  gd_p[[i]] <- gd[gd$Species %like% i,]
}

gd_p2 <- gd_p

for (i in seq_along(plants)) {
  gd_p2[[i]] <- gd_p[[i]][which((gd_p[[i]][,2] >= start_dates21[i] & gd_p[[i]][,2] <= end_dates21[i]) |
                                (gd_p[[i]][,2] >= start_dates22[i] & gd_p[[i]][,2] <= end_dates22[i]) |
                                (gd_p[[i]][,2] >= start_dates23[i] & gd_p[[i]][,2] <= end_dates23[i]) ), ]
}

gd_b <- bind_rows(gd_p2)
gd_b_overall <- dplyr::filter(gd_b, grepl('Overall Appearance', variable))
gd_b_means <- gd_b %>% group_by(Species, variable) %>% summarise(mean = mean(value,na.rm = TRUE))
gd_b_overall_means <- gd_b_means[gd_b_means$variable %like% 'Overall Appearance',]
```

```{R}
# See how many entries are within blooming season 
for (i in seq_along(plants)) {
  print(paste0(plants[i], ": ", nrow(gd_p2[[i]]), "/", nrow(gd_p[[i]])))
  }
```

#Unweighted Mean
```{r}
uw_plotting <- gd_o_means

uw_plotting$vfull <- c('Achilea milleolium', 
                      'Asclepias Speciosa',
                      'Bouteloua gracilis',
                      'Carex pansa',
                      'Eriogonum umbellatum',
                      'Eschscholzia californica',
                      'Festuca californica',
                      'Festuca idahoensis',
                      'Mimulus bifidus',
                      'Monardella villosa',
                      'Penstomon Margarita BOP',
                      'Sisyrinchium bellum')

uw_plotting <- uw_plotting %>% arrange(-mean)

# color assignment
uw_plotting$color_bin <- cut(uw_plotting$mean,
                            breaks = c(0, 3, 3.5, 4, 5),
                            labels = c("low", "medium-low", "medium-high", "high"),
                            right = TRUE)
color_palette <- c("#d11141", "#f37735", "#ffc425", "#00b159")
uw_plotting$color <- color_palette[as.numeric(uw_plotting$color_bin)]

uw_plot <- ggplot(uw_plotting, aes(reorder(Species, -mean), mean)) +
  geom_col(fill = uw_plotting$color) +
  ylim(0,5) +
  labs(x = 'Species',
       y = 'Mean Overall Appearance')+
  theme_linedraw()

```

# Weighted Overall Mean
```{r}
w_plotting <- gd_b_overall_means

w_plotting$vfull <- c('Achilea milleolium', 
                      'Asclepias Speciosa',
                      'Bouteloua gracilis',
                      'Carex pansa',
                      'Eriogonum umbellatum',
                      'Eschscholzia californica',
                      'Festuca  californica',
                      'Festuca idahoensis',
                      'Mimulus bifidus',
                      'Monardella villosa',
                      'Penstomon Margarita BOP',
                      'Sisyrinchium bellum')

w_plotting <- w_plotting %>% arrange(-mean)

w_plotting$color_bin <- cut(w_plotting$mean,
                            breaks = c(0, 3, 3.5, 4, 5),
                            labels = c("low", "medium-low", "medium-high", "high"),
                            right = TRUE)
w_plotting$color <- color_palette[as.numeric(w_plotting$color_bin)]

w_plot <- ggplot(w_plotting, aes(reorder(Species, -mean), mean)) +
  geom_col(fill = w_plotting$color) +
  ylim(0,5) +
  labs(x = 'Species',
       y = 'Mean Overall Appearance') +
  theme_linedraw()

```

```{r}
# Time series for all season
time_series <- ggplot(gd, aes(Timestamp, value)) +
  geom_hline(aes(yintercept=3), color = color_palette[2]) +
  geom_hline(aes(yintercept=3.5), color = color_palette[3]) +
  geom_hline(aes(yintercept=4), color = color_palette[4]) +
  stat_smooth() +
  facet_wrap(~Species) +
  theme_linedraw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = 'Mean Overall Appearance', x = 'Date')
```

```{r}
if (!dir.exists("figs")) {
  dir.create("figs")
}

ggsave("figs/unweighted_means.png", uw_plot, width = 7.5, height = 4, units = 'in')
ggsave("figs/weighted_means.png", w_plot, width = 7.5, height = 4, units = 'in')
ggsave("figs/time_series.png", time_series, width = 7.5, height = 6, units = 'in')
```
